group=com.github.ixtf
version=1.0.0

# Gradle properties
#org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -XX:+UseParallelGC --enable-native-access=ALL-UNNAMED -Dio.netty.noUnsafe=false

# System properties
systemProp.file.encoding=UTF-8
systemProp.pts.enabled=true
systemProp.log4j2.disableJmx=true

#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=10809

